FROM bufbuild/buf:latest
WORKDIR /app
ADD . /app
RUN apk add --update npm go && \
npm install

RUN go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest && \
go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@latest && \
go install google.golang.org/protobuf/cmd/protoc-gen-go@latest && \
go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

ENV PATH=$PATH:/root/go/bin
CMD [ "/bin/sh", "-c", "/usr/local/bin/buf \"$@\"", "--"]