// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: api/note_purchase_agreement/v1/note_purchase_agreement.proto

package notepurchaseagreement

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	NotePurchaseAgreementService_GetNotePurchaseAgreements_FullMethodName   = "/api.note_purchase_agreement.v1.NotePurchaseAgreementService/GetNotePurchaseAgreements"
	NotePurchaseAgreementService_GetNotePurchaseAgreement_FullMethodName    = "/api.note_purchase_agreement.v1.NotePurchaseAgreementService/GetNotePurchaseAgreement"
	NotePurchaseAgreementService_SaveNotePurchaseAgreement_FullMethodName   = "/api.note_purchase_agreement.v1.NotePurchaseAgreementService/SaveNotePurchaseAgreement"
	NotePurchaseAgreementService_GetNotePurchaseAgreementDoc_FullMethodName = "/api.note_purchase_agreement.v1.NotePurchaseAgreementService/GetNotePurchaseAgreementDoc"
)

// NotePurchaseAgreementServiceClient is the client API for NotePurchaseAgreementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotePurchaseAgreementServiceClient interface {
	GetNotePurchaseAgreements(ctx context.Context, in *GetNotePurchaseAgreementsRequest, opts ...grpc.CallOption) (*GetNotePurchaseAgreementsResponse, error)
	GetNotePurchaseAgreement(ctx context.Context, in *GetNotePurchaseAgreementRequest, opts ...grpc.CallOption) (*GetNotePurchaseAgreementResponse, error)
	SaveNotePurchaseAgreement(ctx context.Context, in *SaveNotePurchaseAgreementRequest, opts ...grpc.CallOption) (*SaveNotePurchaseAgreementResponse, error)
	GetNotePurchaseAgreementDoc(ctx context.Context, in *GetNotePurchaseAgreementDocRequest, opts ...grpc.CallOption) (NotePurchaseAgreementService_GetNotePurchaseAgreementDocClient, error)
}

type notePurchaseAgreementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotePurchaseAgreementServiceClient(cc grpc.ClientConnInterface) NotePurchaseAgreementServiceClient {
	return &notePurchaseAgreementServiceClient{cc}
}

func (c *notePurchaseAgreementServiceClient) GetNotePurchaseAgreements(ctx context.Context, in *GetNotePurchaseAgreementsRequest, opts ...grpc.CallOption) (*GetNotePurchaseAgreementsResponse, error) {
	out := new(GetNotePurchaseAgreementsResponse)
	err := c.cc.Invoke(ctx, NotePurchaseAgreementService_GetNotePurchaseAgreements_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notePurchaseAgreementServiceClient) GetNotePurchaseAgreement(ctx context.Context, in *GetNotePurchaseAgreementRequest, opts ...grpc.CallOption) (*GetNotePurchaseAgreementResponse, error) {
	out := new(GetNotePurchaseAgreementResponse)
	err := c.cc.Invoke(ctx, NotePurchaseAgreementService_GetNotePurchaseAgreement_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notePurchaseAgreementServiceClient) SaveNotePurchaseAgreement(ctx context.Context, in *SaveNotePurchaseAgreementRequest, opts ...grpc.CallOption) (*SaveNotePurchaseAgreementResponse, error) {
	out := new(SaveNotePurchaseAgreementResponse)
	err := c.cc.Invoke(ctx, NotePurchaseAgreementService_SaveNotePurchaseAgreement_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notePurchaseAgreementServiceClient) GetNotePurchaseAgreementDoc(ctx context.Context, in *GetNotePurchaseAgreementDocRequest, opts ...grpc.CallOption) (NotePurchaseAgreementService_GetNotePurchaseAgreementDocClient, error) {
	stream, err := c.cc.NewStream(ctx, &NotePurchaseAgreementService_ServiceDesc.Streams[0], NotePurchaseAgreementService_GetNotePurchaseAgreementDoc_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &notePurchaseAgreementServiceGetNotePurchaseAgreementDocClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NotePurchaseAgreementService_GetNotePurchaseAgreementDocClient interface {
	Recv() (*GetNotePurchaseAgreementDocResponse, error)
	grpc.ClientStream
}

type notePurchaseAgreementServiceGetNotePurchaseAgreementDocClient struct {
	grpc.ClientStream
}

func (x *notePurchaseAgreementServiceGetNotePurchaseAgreementDocClient) Recv() (*GetNotePurchaseAgreementDocResponse, error) {
	m := new(GetNotePurchaseAgreementDocResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NotePurchaseAgreementServiceServer is the server API for NotePurchaseAgreementService service.
// All implementations must embed UnimplementedNotePurchaseAgreementServiceServer
// for forward compatibility
type NotePurchaseAgreementServiceServer interface {
	GetNotePurchaseAgreements(context.Context, *GetNotePurchaseAgreementsRequest) (*GetNotePurchaseAgreementsResponse, error)
	GetNotePurchaseAgreement(context.Context, *GetNotePurchaseAgreementRequest) (*GetNotePurchaseAgreementResponse, error)
	SaveNotePurchaseAgreement(context.Context, *SaveNotePurchaseAgreementRequest) (*SaveNotePurchaseAgreementResponse, error)
	GetNotePurchaseAgreementDoc(*GetNotePurchaseAgreementDocRequest, NotePurchaseAgreementService_GetNotePurchaseAgreementDocServer) error
	mustEmbedUnimplementedNotePurchaseAgreementServiceServer()
}

// UnimplementedNotePurchaseAgreementServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNotePurchaseAgreementServiceServer struct {
}

func (UnimplementedNotePurchaseAgreementServiceServer) GetNotePurchaseAgreements(context.Context, *GetNotePurchaseAgreementsRequest) (*GetNotePurchaseAgreementsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNotePurchaseAgreements not implemented")
}
func (UnimplementedNotePurchaseAgreementServiceServer) GetNotePurchaseAgreement(context.Context, *GetNotePurchaseAgreementRequest) (*GetNotePurchaseAgreementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNotePurchaseAgreement not implemented")
}
func (UnimplementedNotePurchaseAgreementServiceServer) SaveNotePurchaseAgreement(context.Context, *SaveNotePurchaseAgreementRequest) (*SaveNotePurchaseAgreementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveNotePurchaseAgreement not implemented")
}
func (UnimplementedNotePurchaseAgreementServiceServer) GetNotePurchaseAgreementDoc(*GetNotePurchaseAgreementDocRequest, NotePurchaseAgreementService_GetNotePurchaseAgreementDocServer) error {
	return status.Errorf(codes.Unimplemented, "method GetNotePurchaseAgreementDoc not implemented")
}
func (UnimplementedNotePurchaseAgreementServiceServer) mustEmbedUnimplementedNotePurchaseAgreementServiceServer() {
}

// UnsafeNotePurchaseAgreementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotePurchaseAgreementServiceServer will
// result in compilation errors.
type UnsafeNotePurchaseAgreementServiceServer interface {
	mustEmbedUnimplementedNotePurchaseAgreementServiceServer()
}

func RegisterNotePurchaseAgreementServiceServer(s grpc.ServiceRegistrar, srv NotePurchaseAgreementServiceServer) {
	s.RegisterService(&NotePurchaseAgreementService_ServiceDesc, srv)
}

func _NotePurchaseAgreementService_GetNotePurchaseAgreements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNotePurchaseAgreementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotePurchaseAgreementServiceServer).GetNotePurchaseAgreements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotePurchaseAgreementService_GetNotePurchaseAgreements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotePurchaseAgreementServiceServer).GetNotePurchaseAgreements(ctx, req.(*GetNotePurchaseAgreementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotePurchaseAgreementService_GetNotePurchaseAgreement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNotePurchaseAgreementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotePurchaseAgreementServiceServer).GetNotePurchaseAgreement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotePurchaseAgreementService_GetNotePurchaseAgreement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotePurchaseAgreementServiceServer).GetNotePurchaseAgreement(ctx, req.(*GetNotePurchaseAgreementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotePurchaseAgreementService_SaveNotePurchaseAgreement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveNotePurchaseAgreementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotePurchaseAgreementServiceServer).SaveNotePurchaseAgreement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotePurchaseAgreementService_SaveNotePurchaseAgreement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotePurchaseAgreementServiceServer).SaveNotePurchaseAgreement(ctx, req.(*SaveNotePurchaseAgreementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotePurchaseAgreementService_GetNotePurchaseAgreementDoc_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetNotePurchaseAgreementDocRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NotePurchaseAgreementServiceServer).GetNotePurchaseAgreementDoc(m, &notePurchaseAgreementServiceGetNotePurchaseAgreementDocServer{stream})
}

type NotePurchaseAgreementService_GetNotePurchaseAgreementDocServer interface {
	Send(*GetNotePurchaseAgreementDocResponse) error
	grpc.ServerStream
}

type notePurchaseAgreementServiceGetNotePurchaseAgreementDocServer struct {
	grpc.ServerStream
}

func (x *notePurchaseAgreementServiceGetNotePurchaseAgreementDocServer) Send(m *GetNotePurchaseAgreementDocResponse) error {
	return x.ServerStream.SendMsg(m)
}

// NotePurchaseAgreementService_ServiceDesc is the grpc.ServiceDesc for NotePurchaseAgreementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotePurchaseAgreementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.note_purchase_agreement.v1.NotePurchaseAgreementService",
	HandlerType: (*NotePurchaseAgreementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNotePurchaseAgreements",
			Handler:    _NotePurchaseAgreementService_GetNotePurchaseAgreements_Handler,
		},
		{
			MethodName: "GetNotePurchaseAgreement",
			Handler:    _NotePurchaseAgreementService_GetNotePurchaseAgreement_Handler,
		},
		{
			MethodName: "SaveNotePurchaseAgreement",
			Handler:    _NotePurchaseAgreementService_SaveNotePurchaseAgreement_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetNotePurchaseAgreementDoc",
			Handler:       _NotePurchaseAgreementService_GetNotePurchaseAgreementDoc_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/note_purchase_agreement/v1/note_purchase_agreement.proto",
}
